# site settings
title: Fundaci贸n Industria Creativa
subtitle: Industria Creativa
email: ficcreativa@gmail.com
description: Esto es un contenido
baseurl: "/" # the subpath of your site, e.g. /blog
url: "fic.ong"# the base hostname & protocol for your site
author: "Fundaci贸n Industrias Creativas"
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: Chile
phone: (+56) 1111111

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/ficcreativa
  Facebook:
  Slack:

# build settings
#=======
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fundaci贸n Industria Creativa

# This is the place to set up the contact form recipient
# email: your-email@example.com

description: > # this means to ignore newlines until "baseurl:"
  Una descripci贸n que debemos conversar
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://fic.ong" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
